name = input("What is your name? ")
age = input("Whats is your age? ")
registered = input("Have you registered yet? ")
print("Your name is:",name)
print("Your age is:",age)
print("Registration Status: ",registered)
